language: node_js
sudo: required
services:
- docker
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
  - node_modules
node_js:
- 6
before_install:
- cd api/
- npm install -g node-gyp
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- npm install -g standard
- docker-compose build
- docker-compose up -d
- sleep 3
- mongo "localhost:27017/nodetest1" --eval "db.dropDatabase();"
script:
- cd ../api
- npm test
- cd ../web-app
- npm install
- npm run e2e
after_success:
- if [ "$TRAVIS_BRANCH" == "master" || "$TRAVIS_BRANCH" == "Dev-Sprint3" ]; then
- docker tag beppproject_express registry.heroku.com/bepp-project/web
- docker login --username=_ --password=0bb9660b-60ca-4694-9c77-cb7ec07c1d55 registry.heroku.com
- docker push registry.heroku.com/bepp-project/web
- fi
after_script:
- docker-compose kill
before_deploy:
- cd ..
- tar cvf release.tgz .
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: dwDVunzk5do0iktpGWFluYo0WuHM+Q/uYnvVz6KMsLFsF+yxPc6uAXmMAqUhEQHMQMKhHgjYBOiheXUBDhFd2OQIYNYi3c8TQQ1qjoZ4ZRN3PGrVg/160dYpQr1rSKwWrOYv0vk2y9CrKn234atN7DKBpXS+z8g0UsErKzUMifvqeM2Fl796H6MHFSsiBcdUwqVW7BDMS0n2IvFk4iWjyLSZdSFLrZUFTGVVSEp3CBWl26rZqXUCg8MQ9W2vVbekPr+Zhs6h9uoXalpEzDMAW/4vmhPGFlsQCVvBBSid5h25I6ecN8KGFQb+67+33gkoJgXZ9HPCr/iEM0TQyfJID7Oq51bQoBP7OjcEDK1IFAuZxNkgm40uxOvVCV/uT17WZUDzMIOhtalHhtjpnVOBc4GWix8+um9Mjt8RQufmm06fb/NTGyzho7vtXxnqyNq7PArio8fxpTyGspQMtcgqxw3n5Esg8HXRfGwKq7pRJLGaWc6gHoSbOaxnwTOaS63yKtyWqs+jNDJJ2fIYj9HsIMXD2wLSjS9EuCOKBFa9xwItQBZne1ridD+fczVxjQoZVPBbkXNElweyuj9SluVB8YyaVEzPKYgDamtHC5pAYeZaLsIVGXjH7qEpgId8jkTqxUZQHttIuzYqPpP3vJ7JXIemRi7zc6ZI86gB5cps+JU=
  file: '"release.tgz"'
  on:
    branch: master
    tags: true
    repo: ElPenguinator/bepp-project
