api:
  build: ./api
  ports:
    - 8080
  links:
    - mongo
  environment:
    - MONGO_HOST=mongo
  command: "node api.js"
mongo:
  image: mongo
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"